title:            dnv aps sn
description:      laser杨万荣
url:              http://blog.sndnvaps.com/
paginate:         10

pygments:         false
permalink:        /:year/:month/:day/:title.html
markdown:         redcarpet
rdiscount:
  extensions:     [smart]

redcarpet:
  extensions: [tables, fenced_code_blocks]

# Theme specific settings
#google_analytics: UA-5266256-5
#disqus_shortname: chchwy

owner:
  name:           dnv aps (dnv aps sn)
  avatar:         'http://images.cnitblog.com/blog/410522/201305/07211949-2f93270a57f945c1a8475ea9519d43e4.jpg'
  bio:            "Hi, I'm dnv aps sn, aka dnv aps . I came, I saw, I coded."
