title:            dnv aps sn
description:      laser杨万荣
url:              https://blog.sndnvaps.com/
paginate:         10

pygments:         false
permalink:        /:year/:month/:day/:title.html
markdown:         kramdown
rdiscount:
  extensions:     [smart]

redcarpet:
  extensions: [tables, fenced_code_blocks]

# Theme specific settings
#google_analytics: UA-5266256-5
#disqus_shortname: chchwy

owner:
  name:           dnv aps (dnv aps sn)
  avatar:         'https://i.loli.net/2019/11/07/oKXHUVIybzJjF51.jpg'
  bio:            "Goditi i benefici del tempo, niente puo'essere permanente."
